### ISSUE TITLE
BanUID

### ISSUE THREAD

**Issue by SossenSystems** [Bluscream/pyTSon_plugins#18]
```
2018-04-26 18:13:34.518984|INFO    |ClientUI      |1  |Calling plugin onMenuItemEvent: scHandlerID=1type=2, menuItemID=27, selectedItemID=107
2018-04-26 18:13:34.519865|ERROR   |pyTSon.PluginHost.onMenuItemEvent|   |Fehler beim Aufruf von onMenuItemEvent im Python Plugin Ban UID: Traceback (most recent call last):
                                                                            File "/home/administrator/.ts3client/plugins/pyTSon/scripts/pluginhost.py", line 640, in onMenuItemEvent
                                                                              plugin.onMenuItemEvent(schid, atype, locid, selectedItemID)
                                                                            File "/home/administrator/.ts3client/plugins/pyTSon/scripts/banUID/__init__.py", line 30, in onMenuItemEvent
                                                                              (err, uid) = ts3lib.getClientVariable(schid, selectedItemID, ts3defines.ClientProperties.CLIENT_UNIQUE_IDENTIFIER)
                                                                          AttributeError: module 'ts3lib' has no attribute 'getClientVariable'

```

**Comment by Bluscream** [comment]
you need the latest beta to run most of my scripts; https://repo.4qt.de/pyTSon/nightlies/latest/
