### ISSUE TITLE
pytson-plugin(channel-watcher)

### ISSUE THREAD

**Issue by ruuser0** [Bluscream/pyTSon_plugins#56]
04.02.2019 19:15:03	pyTSon.PluginHost.activate	Error	Error starting python plugin Channel Watcher: Traceback (most recent call last):
  File "D:/TeamSpeak 3 Client/config/plugins/pyTSon/scripts\pluginhost.py", line 238, in activate
    cls.active[pname] = cls.plugins[pname]()
  File "D:/TeamSpeak 3 Client/config/plugins/pyTSon/scripts\channelWatcher\__init__.py", line 64, in __init__
    schid = ts3lib.getCurrentschid()
AttributeError: module 'ts3lib' has no attribute 'getCurrentschid'

can u help me ?

**Comment by Bluscream** [comment]
Haven't worked with that thing for so long that it will require a complete rewrite probably, sorry. However i can suggest to use alex720/User-Manager
